# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true

ui:
  static_use_hash: true

engines:
  # 启用默认禁用的引擎
  - name: google
    disabled: true
  - name: duckduckgo
    disabled: true
  - name: brave
    disabled: true
  # - name: startpage
  #   disabled: true
  - name: bing
    disabled: true
  - name: wikipedia
    disabled: true
  - name: wikidata
    disabled: true
  # - name: qwant
  #   disabled: true
  # - name: startpage
  #   disabled: true
  # - name: presearch
  #   disabled: false


  # - name: 360search
  #   engine: 360search
  #   shortcut: 360so
  #   disabled: trues
  
  # - name: baidu
  #   engine: baidu
  #   shortcut: baidu
  #   disabled: false
  
  # - name: iqiyi
  #   engine: iqiyi
  #   shortcut: iq
  #   disabled: false

  # - name: acfun
  #   engine: acfun
  #   shortcut: acf
  #   disabled: false



    

server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "888"  # change this!
  limiter: true  # can be disabled for a private instance
  image_proxy: true
ui:
  static_use_hash: true
valkey:
  url: valkey://valkey:6379/0 
  
search:
  safe_search: 0
  autocomplete: ""
  default_lang: ""
  formats:
    - html
    - json
    - csv
    - rss
ratelimit:
    enabled: true
    # 调整每秒允许的请求数
    per_second: 5  
    # 调整每分钟允许的请求数
    per_minute: 60

timeouts:
  total: 10.0
  connect: 6.0

outgoing:
  request_timeout: 20.0
  
network:
  request_args:
    max_redirects: 3
    allow_redirects: true